package com.swatiee;

import java.io.Serializable;

public class Notofication implements Serializable {
	
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 5527258407135657543L;
	
	private long id;
	private int srNum;
	private String taskName;
	private String emailOrPhone;
	private String dateTime;
	private String message;
	
	public Notofication(int srNum, String taskName, String emailOrPhone,
			String message, String dateTime) {
		super();
		this.srNum = srNum;
		this.taskName = taskName;
		this.emailOrPhone = emailOrPhone;
		this.message = message;
		this.dateTime = dateTime;
	}

	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return id;
	}
	public void setSrNum(int srNum) {
		this.srNum = srNum;
	}
	public int getSrNum() {
		return srNum;
	}
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}
	public String getTaskName() {
		return taskName;
	}

	public String getEmailOrPhone() {
		return emailOrPhone;
	}

	public void setEmailOrPhone(String emailOrPhone) {
		this.emailOrPhone = emailOrPhone;
	}

	public String getDateTime() {
		return dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Override
	public String toString() {
		return "Notofication [id=" + id + ", srNum=" + srNum + ", taskName="
				+ taskName + ", emailOrPhone=" + emailOrPhone + ", message="
				+ message + ", dateTime=" + dateTime + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Notofication other = (Notofication) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
