package com.swatiee;

import java.io.Serializable;

public class Task implements Serializable {
	
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 5527258407135652423L;
	
	private long id;
	private String name;
	private String address;
	private String email;
	private String phone;
	private boolean complete;
	private double latitude;
	private double longitude;
	private long expiryInMinutes;
	
	
	public Task(String taskName, String address, double lat, double lng, String email, String phone, int expiryInMinutes) {
		this.name = taskName;
		this.address=address;
		this.email=email;
		this.phone =phone;
		this.setLatitude(lat);
		this.setLongitude(lng);
		this.setExpiryInMinutes(expiryInMinutes);// need to think more abt this - how to handle when travelling in different time zones.
	}
	
	// used by AddTask to pass to a-sync
	public Task(String taskName, String taskAddress, String taskEmail, String taskPhone) {
		this.id = 0;
		this.name = taskName;
		this.address=taskAddress;
		this.email=taskEmail;
		this.phone =taskPhone;	}

	public void setId(long id) {
		this.id = id;
	}

	public long getId() {
		return id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
	
	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress() {
		return address;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLatitude() {
		return latitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return email;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPhone() {
		return phone;
	}

	public void setExpiryInMinutes(long expiryInMinutes) {
		this.expiryInMinutes = expiryInMinutes;
	}

	public long getExpiryInMinutes() {
		return expiryInMinutes;
	}

	public void setComplete(boolean complete) {
		this.complete = complete;
	}

	public boolean isComplete() {
		return complete;
	}

	public void toggleComplete() {
		complete = !complete;
	}
	
	@Override
	public String toString() {
		return "Task [id=" + id + ", name=" + name + ", address=" + address
				+ ", email=" + email + ", phone=" + phone + ", latitude="
				+ latitude + ", longitude=" + longitude + ", expiryInMinutes="
				+ expiryInMinutes + "]";
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Task))
			return false;
		Task other = (Task) obj;
		if (id != other.id)
			return false;
		return true;
	}
	
	
}
